### ISSUE TITLE
作者你好，我仔细看过你的实现步骤了，但是发现给出的训练好的模型的谷歌云盘链接已经失效，能否重新给个链接呢？

### ISSUE THREAD

**Issue by HELL-TO-HEAVEN** [hwwu/ctpn-crnn#4]

**Comment by hwwu** [comment]
emmmm,谷歌云盘空间不够，我就把以前的东西清了，这个训练起来很快的，你可以试着自己训练一下，哪里遇到问题可以一起探讨

**Comment by HELL-TO-HEAVEN** [comment]
如果我没看错的话，ctpn的训练只需要原图片与图片旋转后的标签label.csv文件，关键是后者，请问若有大量图片数据的话，如何制作该label.csv文件？难道只能通过手动慢慢的打标签？？？效率未免太低了。
  综上所述，若作者您还留有数据集与csv文件的话，恳请私发一份。除此之外，目测后续的训练过程应该不存在其他问题了。

**Comment by hwwu** [comment]
当时参加的这个比赛，https://www.datafountain.cn/competitions/334/datasets，你可以下载这里的训练集。地址：http://datafountain.int-yt.com/DCIC2019/334/traindataset.zip

**Comment by HELL-TO-HEAVEN** [comment]
%作者你好，我crnn的训练过程让我有点懵逼，
![image](https://user-images.githubusercontent.com/44086116/61895837-2e3f9080-af46-11e9-96f2-f28d550042b1.png)。。几个小时过去了，精度几乎是零，我不禁怀疑是否是数据处理出错了：
1、tolmdb.py运行之后产生了data.mdb和lock.mdb，这个lock.mdb的产生是否是正常的？后续是否被训练的程序使用？
2、我分别对训练数据与验证数据运行了lmdb.py，各自产生其mdb文件；
3、--cuda参数真的不用设为True吗，我这边是cpu占了90%以上，gpu内存只占用了一个多G。。
4、若以上都正确，请问为什么精度如此低呢？

**Comment by hwwu** [comment]
> %作者你好，我crnn的训练过程让我有点懵逼，
> ![image](https://user-images.githubusercontent.com/44086116/61895837-2e3f9080-af46-11e9-96f2-f28d550042b1.png)
> ![image](https://user-images.githubusercontent.com/44086116/61954838-571a6100-afec-11e9-873c-38a5b490a873.png)
> 。。30个小时过去了，精度还不到50%，而且这训练速度也太慢了吧？！
> --cuda的确已经写上了，但是我这边是cpu占了90%以上，gpu内存却只占用了一个多G。。关键是实在是太慢啦。精度也上不去

你的数据量是多少,迭代了几个epoch，GPU只占1G应该是有问题的，loss在将低，说明是在正常训练，可以检查一下cuda和pytorch版本，然后用pytorch训练一个mnist小模型，看是否能正确调用GPU训练
